// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorneoJudo.Data;

namespace TorneoJudo.Migrations
{
    [DbContext(typeof(AtletaContext))]
    partial class AtletaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TorneoJudo.Models.Atleta", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cintura");

                    b.Property<string>("cognome");

                    b.Property<string>("foreignKeySquadra");

                    b.Property<string>("nome");

                    b.Property<int>("peso");

                    b.Property<string>("sesso")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<int>("vittorie");

                    b.HasKey("id");

                    b.ToTable("Atleta");
                });
#pragma warning restore 612, 618
        }
    }
}
